# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_dt', models.DateField()),
                ('let_points', models.IntegerField()),
                ('is_finished', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='cue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('material', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('let_points', models.IntegerField()),
                ('get_points', models.IntegerField()),
                ('oppo_points', models.IntegerField()),
                ('is_win', models.CharField(max_length=1)),
                ('max_break', models.IntegerField()),
                ('memo', models.CharField(max_length=200)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_frame', to='snooker.campaign')),
                ('cue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snooker.cue')),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('is_show', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('road', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_player', to='snooker.group')),
            ],
        ),
        migrations.AddField(
            model_name='cue',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snooker.player'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snooker.cue'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='gym',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snooker.gym'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='opponent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snooker.player'),
        ),
    ]
